apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-data
  namespace: cattle-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
